spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:inventory;MODE=PostgreSQL
    username: jpa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 8081

debug: false
