insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (1, 68, 'Bloodsport', 'Well-Worn', false, 49.95);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (2, 80, 'Elite Build', 'WW', false, 524.06);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (3, 75, 'Aquamarine Revenge', 'BS', true, 230.23);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (4, 73, 'Asiimov', 'Battle-Scarred', true, 439.03);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (5, 71, 'Vulcan', 'WW', true, 473.11);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (6, 32, 'Hydroponic', 'MW', false, 520.96);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (7, 64, 'Elite Build', 'BS', false, 53.38);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (8, 2, 'Phobos', 'Well-Worn', true, 911.7);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (9, 65, 'Frontside Misty', 'FN', false, 1102.19);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (10, 93, 'Aquamarine Revenge', 'WW', false, 23.05);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (11, 86, 'Jungle Spray', 'BS', false, 1378.98);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (12, 80, 'Asiimov', 'FT', true, 890.95);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (13, 72, 'Vulcan', 'WW', false, 147.91);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (14, 76, 'Frontside Misty', 'Factory New', true, 761.41);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (15, 42, 'Redline', 'BS', false, 904.07);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (16, 92, 'Bloodsport', 'FN', true, 274.73);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (17, 82, 'Neon Revolution', 'FN', true, 795.84);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (18, 68, 'Aquamarine Revenge', 'Battle-Scarred', true, 384.13);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (19, 40, 'Aquamarine Revenge', 'Well-Worn', false, 1452.9);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (20, 97, 'Jungle Spray', 'BS', false, 246.38);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (21, 62, 'Wasteland Rebel', 'MW', true, 957.92);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (22, 14, 'Hydroponic', 'FN', false, 615.74);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (23, 86, 'Elite Build', 'FN', true, 1296.96);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (24, 71, 'Elite Build', 'Battle-Scarred', false, 608.1);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (25, 32, 'Redline', 'Battle-Scarred', true, 404.85);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (26, 55, 'Jungle Spray', 'Minimal Wear', true, 523.46);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (27, 42, 'Bloodsport', 'FN', true, 600.62);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (28, 48, 'Asiimov', 'Factory New', true, 342.83);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (29, 67, 'Neon Revolution', 'WW', false, 892.04);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (30, 36, 'Wasteland Rebel', 'Battle-Scarred', false, 174.41);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (31, 71, 'Phobos', 'BS', false, 253.44);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (32, 28, 'Phobos', 'Field-Tested', true, 1337.91);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (33, 38, 'Redline', 'Battle-Scarred', true, 1377.05);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (34, 91, 'Phobos', 'MW', true, 1400.78);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (35, 72, 'Jungle Spray', 'WW', false, 143.07);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (36, 55, 'Bloodsport', 'Minimal Wear', true, 497.72);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (37, 6, 'Jungle Spray', 'FT', true, 35.76);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (38, 46, 'Redline', 'WW', true, 1066.28);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (39, 32, 'Wasteland Rebel', 'FT', false, 449.9);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (40, 65, 'Bloodsport', 'BS', false, 16.64);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (41, 55, 'Case Hardened', 'Well-Worn', true, 166.57);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (42, 63, 'Jungle Spray', 'WW', true, 1175.82);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (43, 52, 'Phobos', 'FN', false, 1006.43);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (44, 28, 'Bloodsport', 'FN', false, 708.81);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (45, 3, 'Redline', 'WW', false, 381.09);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (46, 68, 'Frontside Misty', 'Battle-Scarred', false, 83.57);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (47, 19, 'Wasteland Rebel', 'Minimal Wear', false, 1008.02);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (48, 29, 'Redline', 'Field-Tested', true, 958.35);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (49, 93, 'Fuel Injector', 'BS', false, 461.29);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (50, 54, 'Case Hardened', 'WW', true, 688.96);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (51, 46, 'Point Disarray', 'FN', true, 773.99);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (52, 10, 'Redline', 'WW', true, 1180.32);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (53, 68, 'Neon Revolution', 'FT', true, 717.3);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (54, 76, 'Asiimov', 'FT', false, 884.0);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (55, 48, 'Point Disarray', 'FN', false, 270.71);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (56, 65, 'Asiimov', 'Field-Tested', true, 146.44);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (57, 62, 'Frontside Misty', 'FN', false, 38.87);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (58, 31, 'Vulcan', 'Factory New', true, 22.58);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (59, 55, 'Hydroponic', 'Minimal Wear', false, 1265.97);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (60, 14, 'Aquamarine Revenge', 'Factory New', false, 1331.61);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (61, 83, 'Frontside Misty', 'Battle-Scarred', true, 450.27);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (62, 54, 'Hydroponic', 'WW', true, 489.07);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (63, 65, 'Neon Revolution', 'FN', false, 29.82);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (64, 18, 'Point Disarray', 'BS', false, 1356.94);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (65, 52, 'Fuel Injector', 'WW', true, 229.04);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (66, 80, 'Neon Revolution', 'FN', true, 21.61);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (67, 65, 'Phobos', 'MW', false, 1082.4);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (68, 74, 'Case Hardened', 'Factory New', false, 209.25);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (69, 88, 'Hydroponic', 'WW', false, 1436.14);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (70, 63, 'Point Disarray', 'Battle-Scarred', false, 283.23);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (71, 60, 'Vulcan', 'FN', true, 1315.26);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (72, 34, 'Point Disarray', 'Field-Tested', false, 896.45);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (73, 65, 'Fuel Injector', 'MW', true, 165.47);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (74, 23, 'Wasteland Rebel', 'FN', false, 354.42);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (75, 32, 'Vulcan', 'WW', false, 601.71);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (76, 28, 'Vulcan', 'FT', false, 1200.92);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (77, 4, 'Asiimov', 'BS', false, 711.22);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (78, 13, 'Vulcan', 'BS', true, 311.27);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (79, 18, 'Aquamarine Revenge', 'FT', false, 889.67);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (80, 17, 'Frontside Misty', 'BS', false, 1122.09);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (81, 88, 'Frontside Misty', 'Factory New', false, 1123.16);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (82, 27, 'Frontside Misty', 'BS', true, 1436.09);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (83, 38, 'Frontside Misty', 'WW', true, 1118.78);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (84, 15, 'Bloodsport', 'Well-Worn', false, 80.29);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (85, 88, 'Redline', 'BS', true, 807.31);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (86, 19, 'Phobos', 'FN', false, 1355.73);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (87, 49, 'Vulcan', 'FT', false, 569.54);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (88, 17, 'Asiimov', 'Battle-Scarred', false, 1333.09);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (89, 81, 'Vulcan', 'Battle-Scarred', false, 626.61);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (90, 15, 'Vulcan', 'Well-Worn', true, 1443.18);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (91, 40, 'Bloodsport', 'Well-Worn', false, 807.13);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (92, 59, 'Hydroponic', 'FT', true, 763.7);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (93, 87, 'Jungle Spray', 'FN', false, 927.65);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (94, 11, 'Point Disarray', 'Field-Tested', true, 56.95);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (95, 8, 'Elite Build', 'Field-Tested', true, 1350.06);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (96, 34, 'Point Disarray', 'Well-Worn', true, 798.29);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (97, 15, 'Asiimov', 'WW', true, 477.32);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (98, 91, 'Wasteland Rebel', 'FN', false, 609.41);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (99, 34, 'Hydroponic', 'FN', false, 257.0);
insert into inventory (gun_id, player_id, gun_name, gun_status, gun_ST, gun_price) values (100, 25, 'Jungle Spray', 'MW', false, 1224.06);
