insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (17, 'Hydra, M4A1-S', 'Minimal Wear (MW)', false, 334.24, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (83, 'Dragon Lore, USP-S', 'Factory New (FN)', true, 624.0, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (58, 'Monkey Business, SG 553', 'Factory New (FN)', true, 558.6, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (62, 'Asiimov, Nova', 'Factory New (FN)', true, 461.58, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (45, 'Howl, AWP', 'Battle-Scarred (BS)', true, 460.38, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (71, 'AK-47', 'Field-Tested (FT)', true, 133.63, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (87, 'Isaac, UMP-45', 'Battle-Scarred (BS)', false, 805.0, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (34, 'Rocket Pop, MP9', 'Minimal Wear (MW)', true, 254.96, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (49, 'Pulse, SSG 08', 'Well-Worn (WW)', true, 161.54, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (35, 'Hydra, M4A1-S', 'Minimal Wear (MW)', false, 462.13, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (74, 'Blaze, P250', 'Field-Tested (FT)', true, 500.86, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (18, 'Howl, AWP', 'Well-Worn (WW)', false, 841.87, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (82, 'AK-47', 'Battle-Scarred (BS)', false, 110.19, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (11, 'Fade, Desert Eagle', 'Factory New (FN)', false, 277.03, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (60, 'Isaac, UMP-45', 'Factory New (FN)', true, 62.72, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (58, 'Rocket Pop, MP9', 'Minimal Wear (MW)', false, 690.52, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (96, 'Vulcan, M4A4', 'Battle-Scarred (BS)', true, 16.94, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (52, 'Blood in the Water, P90', 'Field-Tested (FT)', true, 580.09, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (28, 'Neon Rider', 'Field-Tested (FT)', true, 685.97, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (59, 'Blood in the Water, P90', 'Minimal Wear (MW)', true, 676.04, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (35, 'Mecha Industries, Tec-9', 'Minimal Wear (MW)', true, 452.53, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (9, 'Mecha Industries, Tec-9', 'Minimal Wear (MW)', true, 679.37, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (90, 'Hyper Beast, XM1014', 'Battle-Scarred (BS)', false, 569.82, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (92, 'Rocket Pop, MP9', 'Field-Tested (FT)', false, 658.27, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (6, 'Neon Rider', 'Minimal Wear (MW)', true, 362.89, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (38, 'Fade, Desert Eagle', 'Well-Worn (WW)', false, 613.79, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (17, 'Blood in the Water, P90', 'Minimal Wear (MW)', false, 284.59, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (77, 'Primal Saber, Five-SeveN', 'Well-Worn (WW)', false, 134.37, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (8, 'Primal Saber, Five-SeveN', 'Battle-Scarred (BS)', true, 954.26, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (2, 'Kill Confirmed, Glock-18', 'Field-Tested (FT)', true, 976.0, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (49, 'Blaze, P250', 'Factory New (FN)', true, 240.37, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (11, 'Roll Cage, Galil AR', 'Factory New (FN)', false, 203.51, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (88, 'Blaze, P250', 'Well-Worn (WW)', false, 227.08, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (4, 'Asiimov, Nova', 'Minimal Wear (MW)', false, 258.72, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (15, 'Blaze, P250', 'Factory New (FN)', false, 128.42, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (91, 'Vulcan, M4A4', 'Battle-Scarred (BS)', true, 596.89, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (56, 'Monkey Business, SG 553', 'Well-Worn (WW)', false, 492.37, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (31, 'Dragon Lore, USP-S', 'Minimal Wear (MW)', true, 962.53, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (46, 'Neon Rider', 'Factory New (FN)', false, 442.16, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (25, 'Fade, Desert Eagle', 'Field-Tested (FT)', false, 246.47, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (16, 'Rocket Pop, MP9', 'Factory New (FN)', true, 530.06, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (8, 'Rocket Pop, MP9', 'Field-Tested (FT)', false, 647.04, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (40, 'Fade, Desert Eagle', 'Battle-Scarred (BS)', false, 852.95, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (15, 'Blood in the Water, P90', 'Minimal Wear (MW)', true, 363.07, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (42, 'Pulse, SSG 08', 'Minimal Wear (MW)', false, 521.87, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (79, 'Monkey Business, SG 553', 'Minimal Wear (MW)', false, 4.75, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (76, 'Roll Cage, Galil AR', 'Well-Worn (WW)', false, 993.12, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (57, 'Kill Confirmed, Glock-18', 'Battle-Scarred (BS)', false, 337.26, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (6, 'Roll Cage, Galil AR', 'Minimal Wear (MW)', true, 467.97, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (47, 'Mecha Industries, Tec-9', 'Field-Tested (FT)', false, 684.44, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (82, 'Mecha Industries, Tec-9', 'Field-Tested (FT)', true, 744.46, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (51, 'Black Tie, MAC-10', 'Well-Worn (WW)', false, 218.21, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (88, 'Monkey Business, SG 553', 'Factory New (FN)', false, 166.81, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (79, 'Hyper Beast, XM1014', 'Minimal Wear (MW)', true, 541.41, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (38, 'Isaac, UMP-45', 'Factory New (FN)', false, 381.36, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (25, 'Blaze, P250', 'Battle-Scarred (BS)', false, 633.03, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (42, 'Blaze, P250', 'Battle-Scarred (BS)', true, 270.45, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (20, 'Hydra, M4A1-S', 'Field-Tested (FT)', true, 779.75, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (39, 'Rocket Pop, MP9', 'Well-Worn (WW)', false, 42.43, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (34, 'Asiimov, FAMAS', 'Minimal Wear (MW)', true, 140.44, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (46, 'Blood in the Water, P90', 'Battle-Scarred (BS)', false, 25.83, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (15, 'Vulcan, M4A4', 'Well-Worn (WW)', true, 317.87, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (30, 'Asiimov, Nova', 'Field-Tested (FT)', true, 581.0, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (90, 'Hydra, M4A1-S', 'Well-Worn (WW)', true, 978.9, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (44, 'Isaac, UMP-45', 'Field-Tested (FT)', false, 732.06, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (64, 'Vulcan, M4A4', 'Field-Tested (FT)', false, 708.44, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (72, 'Asiimov, FAMAS', 'Factory New (FN)', true, 199.44, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (42, 'Fade, Desert Eagle', 'Factory New (FN)', true, 877.27, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (72, 'Pulse, SSG 08', 'Minimal Wear (MW)', true, 154.36, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (84, 'Black Tie, MAC-10', 'Well-Worn (WW)', false, 391.73, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (97, 'Vulcan, M4A4', 'Field-Tested (FT)', false, 201.8, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (87, 'Blood in the Water, P90', 'Field-Tested (FT)', true, 473.22, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (56, 'Fade, Desert Eagle', 'Minimal Wear (MW)', false, 801.26, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (44, 'Blaze, P250', 'Well-Worn (WW)', true, 241.87, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (96, 'Fade, Desert Eagle', 'Battle-Scarred (BS)', false, 588.6, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (85, 'Blood in the Water, P90', 'Field-Tested (FT)', false, 162.42, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (30, 'Hydra, M4A1-S', 'Battle-Scarred (BS)', true, 677.96, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (68, 'Roll Cage, Galil AR', 'Well-Worn (WW)', false, 568.98, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (84, 'Asiimov, Nova', 'Field-Tested (FT)', false, 297.19, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (93, 'Fade, Desert Eagle', 'Field-Tested (FT)', false, 745.23, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (53, 'Blaze, P250', 'Well-Worn (WW)', false, 914.45, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (99, 'Howl, AWP', 'Well-Worn (WW)', true, 807.11, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (72, 'Neon Rider', 'Battle-Scarred (BS)', false, 979.72, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (53, 'Pulse, SSG 08', 'Field-Tested (FT)', true, 676.2, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (3, 'Isaac, UMP-45', 'Well-Worn (WW)', false, 267.25, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (34, 'Rocket Pop, MP9', 'Well-Worn (WW)', false, 203.2, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (95, 'Hyper Beast, XM1014', 'Battle-Scarred (BS)', false, 434.72, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (39, 'Hydra, M4A1-S', 'Field-Tested (FT)', false, 20.82, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (94, 'Dragon Lore, USP-S', 'Well-Worn (WW)', false, 235.72, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (66, 'Primal Saber, Five-SeveN', 'Minimal Wear (MW)', false, 755.68, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (86, 'Roll Cage, Galil AR', 'Well-Worn (WW)', true, 968.55, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (41, 'Neon Rider', 'Battle-Scarred (BS)', true, 60.58, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (42, 'AK-47', 'Minimal Wear (MW)', true, 245.82, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (83, 'Isaac, UMP-45', 'Well-Worn (WW)', true, 368.68, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (84, 'Asiimov, FAMAS', 'Minimal Wear (MW)', false, 307.85, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (18, 'Mecha Industries, Tec-9', 'Field-Tested (FT)', false, 152.73, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (14, 'Isaac, UMP-45', 'Factory New (FN)', true, 244.46, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (52, 'Asiimov, Nova', 'Battle-Scarred (BS)', false, 157.47, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (12, 'Howl, AWP', 'Field-Tested (FT)', false, 628.49, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (7, 'Rocket Pop, MP9', 'Well-Worn (WW)', false, 474.36, true);