insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (17, 'Hydra, M4A1-S', 'Minimal Wear (MW)', false, 334.24, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (83, 'Dragon Lore, USP-S', 'Factory New (FN)', true, 624.0, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (58, 'Monkey Business, SG 553', 'Factory New (FN)', true, 558.6, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (62, 'Asiimov, Nova', 'Factory New (FN)', true, 461.58, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (45, 'Howl, AWP', 'Battle-Scarred (BS)', true, 460.38, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (71, 'AK-47', 'Field-Tested (FT)', true, 133.63, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (87, 'Isaac, UMP-45', 'Battle-Scarred (BS)', false, 805.0, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (34, 'Rocket Pop, MP9', 'Minimal Wear (MW)', true, 254.96, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (49, 'Pulse, SSG 08', 'Well-Worn (WW)', true, 161.54, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (35, 'Hydra, M4A1-S', 'Minimal Wear (MW)', false, 462.13, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (74, 'Blaze, P250', 'Field-Tested (FT)', true, 500.86, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (18, 'Howl, AWP', 'Well-Worn (WW)', false, 841.87, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (82, 'AK-47', 'Battle-Scarred (BS)', false, 110.19, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (11, 'Fade, Desert Eagle', 'Factory New (FN)', false, 277.03, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (60, 'Isaac, UMP-45', 'Factory New (FN)', true, 62.72, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (58, 'Rocket Pop, MP9', 'Minimal Wear (MW)', false, 690.52, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (96, 'Vulcan, M4A4', 'Battle-Scarred (BS)', true, 16.94, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (52, 'Blood in the Water, P90', 'Field-Tested (FT)', true, 580.09, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (28, 'Neon Rider', 'Field-Tested (FT)', true, 685.97, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (59, 'Blood in the Water, P90', 'Minimal Wear (MW)', true, 676.04, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (35, 'Mecha Industries, Tec-9', 'Minimal Wear (MW)', true, 452.53, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (9, 'Mecha Industries, Tec-9', 'Minimal Wear (MW)', true, 679.37, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (90, 'Hyper Beast, XM1014', 'Battle-Scarred (BS)', false, 569.82, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (92, 'Rocket Pop, MP9', 'Field-Tested (FT)', false, 658.27, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (6, 'Neon Rider', 'Minimal Wear (MW)', true, 362.89, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (38, 'Fade, Desert Eagle', 'Well-Worn (WW)', false, 613.79, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (17, 'Blood in the Water, P90', 'Minimal Wear (MW)', false, 284.59, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (77, 'Primal Saber, Five-SeveN', 'Well-Worn (WW)', false, 134.37, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (8, 'Primal Saber, Five-SeveN', 'Battle-Scarred (BS)', true, 954.26, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (2, 'Kill Confirmed, Glock-18', 'Field-Tested (FT)', true, 976.0, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (49, 'Blaze, P250', 'Factory New (FN)', true, 240.37, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (11, 'Roll Cage, Galil AR', 'Factory New (FN)', false, 203.51, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (88, 'Blaze, P250', 'Well-Worn (WW)', false, 227.08, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (4, 'Asiimov, Nova', 'Minimal Wear (MW)', false, 258.72, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (15, 'Blaze, P250', 'Factory New (FN)', false, 128.42, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (91, 'Vulcan, M4A4', 'Battle-Scarred (BS)', true, 596.89, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (56, 'Monkey Business, SG 553', 'Well-Worn (WW)', false, 492.37, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (31, 'Dragon Lore, USP-S', 'Minimal Wear (MW)', true, 962.53, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (46, 'Neon Rider', 'Factory New (FN)', false, 442.16, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (25, 'Fade, Desert Eagle', 'Field-Tested (FT)', false, 246.47, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (16, 'Rocket Pop, MP9', 'Factory New (FN)', true, 530.06, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (8, 'Rocket Pop, MP9', 'Field-Tested (FT)', false, 647.04, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (40, 'Fade, Desert Eagle', 'Battle-Scarred (BS)', false, 852.95, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (15, 'Blood in the Water, P90', 'Minimal Wear (MW)', true, 363.07, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (42, 'Pulse, SSG 08', 'Minimal Wear (MW)', false, 521.87, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (79, 'Monkey Business, SG 553', 'Minimal Wear (MW)', false, 4.75, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (76, 'Roll Cage, Galil AR', 'Well-Worn (WW)', false, 993.12, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (57, 'Kill Confirmed, Glock-18', 'Battle-Scarred (BS)', false, 337.26, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (6, 'Roll Cage, Galil AR', 'Minimal Wear (MW)', true, 467.97, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (47, 'Mecha Industries, Tec-9', 'Field-Tested (FT)', false, 684.44, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (82, 'Mecha Industries, Tec-9', 'Field-Tested (FT)', true, 744.46, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (51, 'Black Tie, MAC-10', 'Well-Worn (WW)', false, 218.21, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (88, 'Monkey Business, SG 553', 'Factory New (FN)', false, 166.81, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (79, 'Hyper Beast, XM1014', 'Minimal Wear (MW)', true, 541.41, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (38, 'Isaac, UMP-45', 'Factory New (FN)', false, 381.36, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (25, 'Blaze, P250', 'Battle-Scarred (BS)', false, 633.03, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (42, 'Blaze, P250', 'Battle-Scarred (BS)', true, 270.45, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (20, 'Hydra, M4A1-S', 'Field-Tested (FT)', true, 779.75, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (39, 'Rocket Pop, MP9', 'Well-Worn (WW)', false, 42.43, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (34, 'Asiimov, FAMAS', 'Minimal Wear (MW)', true, 140.44, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (46, 'Blood in the Water, P90', 'Battle-Scarred (BS)', false, 25.83, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (15, 'Vulcan, M4A4', 'Well-Worn (WW)', true, 317.87, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (30, 'Asiimov, Nova', 'Field-Tested (FT)', true, 581.0, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (90, 'Hydra, M4A1-S', 'Well-Worn (WW)', true, 978.9, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (44, 'Isaac, UMP-45', 'Field-Tested (FT)', false, 732.06, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (64, 'Vulcan, M4A4', 'Field-Tested (FT)', false, 708.44, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (72, 'Asiimov, FAMAS', 'Factory New (FN)', true, 199.44, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (42, 'Fade, Desert Eagle', 'Factory New (FN)', true, 877.27, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (72, 'Pulse, SSG 08', 'Minimal Wear (MW)', true, 154.36, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (84, 'Black Tie, MAC-10', 'Well-Worn (WW)', false, 391.73, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (97, 'Vulcan, M4A4', 'Field-Tested (FT)', false, 201.8, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (87, 'Blood in the Water, P90', 'Field-Tested (FT)', true, 473.22, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (56, 'Fade, Desert Eagle', 'Minimal Wear (MW)', false, 801.26, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (44, 'Blaze, P250', 'Well-Worn (WW)', true, 241.87, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (96, 'Fade, Desert Eagle', 'Battle-Scarred (BS)', false, 588.6, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (85, 'Blood in the Water, P90', 'Field-Tested (FT)', false, 162.42, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (30, 'Hydra, M4A1-S', 'Battle-Scarred (BS)', true, 677.96, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (68, 'Roll Cage, Galil AR', 'Well-Worn (WW)', false, 568.98, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (84, 'Asiimov, Nova', 'Field-Tested (FT)', false, 297.19, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (93, 'Fade, Desert Eagle', 'Field-Tested (FT)', false, 745.23, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (53, 'Blaze, P250', 'Well-Worn (WW)', false, 914.45, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (99, 'Howl, AWP', 'Well-Worn (WW)', true, 807.11, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (72, 'Neon Rider', 'Battle-Scarred (BS)', false, 979.72, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (53, 'Pulse, SSG 08', 'Field-Tested (FT)', true, 676.2, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (3, 'Isaac, UMP-45', 'Well-Worn (WW)', false, 267.25, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (34, 'Rocket Pop, MP9', 'Well-Worn (WW)', false, 203.2, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (95, 'Hyper Beast, XM1014', 'Battle-Scarred (BS)', false, 434.72, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (39, 'Hydra, M4A1-S', 'Field-Tested (FT)', false, 20.82, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (94, 'Dragon Lore, USP-S', 'Well-Worn (WW)', false, 235.72, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (66, 'Primal Saber, Five-SeveN', 'Minimal Wear (MW)', false, 755.68, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (86, 'Roll Cage, Galil AR', 'Well-Worn (WW)', true, 968.55, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (41, 'Neon Rider', 'Battle-Scarred (BS)', true, 60.58, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (42, 'AK-47', 'Minimal Wear (MW)', true, 245.82, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (83, 'Isaac, UMP-45', 'Well-Worn (WW)', true, 368.68, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (84, 'Asiimov, FAMAS', 'Minimal Wear (MW)', false, 307.85, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (18, 'Mecha Industries, Tec-9', 'Field-Tested (FT)', false, 152.73, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (14, 'Isaac, UMP-45', 'Factory New (FN)', true, 244.46, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (52, 'Asiimov, Nova', 'Battle-Scarred (BS)', false, 157.47, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (12, 'Howl, AWP', 'Field-Tested (FT)', false, 628.49, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (7, 'Rocket Pop, MP9', 'Well-Worn (WW)', false, 474.36, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (79, 'Pulse, SSG 08', 'Field-Tested (FT)', true, 301.48, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (3, 'Howl, AWP', 'Factory New (FN)', true, 476.86, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (15, 'Kill Confirmed, Glock-18', 'Factory New (FN)', false, 575.93, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (64, 'Blaze, P250', 'Minimal Wear (MW)', false, 448.82, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (16, 'Pulse, SSG 08', 'Battle-Scarred (BS)', true, 698.96, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (84, 'Asiimov, FAMAS', 'Field-Tested (FT)', true, 926.92, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (80, 'Blood in the Water, P90', 'Well-Worn (WW)', true, 825.07, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (26, 'Black Tie, MAC-10', 'Factory New (FN)', true, 755.43, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (19, 'Rocket Pop, MP9', 'Well-Worn (WW)', false, 98.17, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (89, 'Mecha Industries, Tec-9', 'Factory New (FN)', false, 731.2, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (17, 'Blaze, P250', 'Factory New (FN)', true, 453.9, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (53, 'Monkey Business, SG 553', 'Minimal Wear (MW)', true, 646.41, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (63, 'Fade, Desert Eagle', 'Field-Tested (FT)', false, 618.14, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (24, 'Rocket Pop, MP9', 'Well-Worn (WW)', true, 210.28, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (68, 'Kill Confirmed, Glock-18', 'Field-Tested (FT)', false, 109.85, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (92, 'Isaac, UMP-45', 'Battle-Scarred (BS)', true, 965.89, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (18, 'Roll Cage, Galil AR', 'Minimal Wear (MW)', false, 618.66, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (26, 'Rocket Pop, MP9', 'Battle-Scarred (BS)', true, 232.48, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (74, 'AK-47', 'Well-Worn (WW)', false, 886.35, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (71, 'Primal Saber, Five-SeveN', 'Minimal Wear (MW)', false, 767.75, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (14, 'Pulse, SSG 08', 'Well-Worn (WW)', false, 29.36, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (49, 'Hyper Beast, XM1014', 'Battle-Scarred (BS)', true, 846.88, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (55, 'Monkey Business, SG 553', 'Battle-Scarred (BS)', false, 522.97, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (94, 'Isaac, UMP-45', 'Minimal Wear (MW)', true, 678.47, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (42, 'Blaze, P250', 'Well-Worn (WW)', true, 951.39, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (9, 'AK-47', 'Well-Worn (WW)', false, 669.09, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (96, 'Rocket Pop, MP9', 'Field-Tested (FT)', false, 767.35, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (54, 'Vulcan, M4A4', 'Battle-Scarred (BS)', true, 572.72, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (90, 'Fade, Desert Eagle', 'Minimal Wear (MW)', false, 410.5, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (57, 'Primal Saber, Five-SeveN', 'Minimal Wear (MW)', true, 966.77, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (100, 'Pulse, SSG 08', 'Factory New (FN)', true, 189.24, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (39, 'Dragon Lore, USP-S', 'Field-Tested (FT)', true, 287.04, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (39, 'Kill Confirmed, Glock-18', 'Field-Tested (FT)', true, 470.97, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (6, 'Neon Rider', 'Well-Worn (WW)', false, 244.09, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (16, 'Fade, Desert Eagle', 'Minimal Wear (MW)', false, 626.66, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (47, 'Hyper Beast, XM1014', 'Well-Worn (WW)', true, 722.68, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (54, 'Neon Rider', 'Battle-Scarred (BS)', true, 507.57, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (67, 'Pulse, SSG 08', 'Factory New (FN)', true, 238.86, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (40, 'Black Tie, MAC-10', 'Field-Tested (FT)', false, 743.13, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (97, 'Blood in the Water, P90', 'Factory New (FN)', true, 816.52, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (40, 'Dragon Lore, USP-S', 'Factory New (FN)', true, 456.48, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (35, 'Primal Saber, Five-SeveN', 'Minimal Wear (MW)', false, 617.43, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (57, 'Blaze, P250', 'Well-Worn (WW)', false, 403.94, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (7, 'Asiimov, FAMAS', 'Battle-Scarred (BS)', true, 754.31, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (40, 'Neon Rider', 'Minimal Wear (MW)', false, 690.15, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (2, 'Kill Confirmed, Glock-18', 'Well-Worn (WW)', true, 884.87, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (25, 'Blood in the Water, P90', 'Well-Worn (WW)', true, 181.92, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (22, 'Roll Cage, Galil AR', 'Field-Tested (FT)', false, 473.4, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (70, 'Vulcan, M4A4', 'Battle-Scarred (BS)', true, 805.63, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (100, 'Mecha Industries, Tec-9', 'Field-Tested (FT)', true, 737.1, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (13, 'Primal Saber, Five-SeveN', 'Field-Tested (FT)', false, 537.25, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (5, 'Neon Rider', 'Field-Tested (FT)', false, 568.14, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (92, 'Monkey Business, SG 553', 'Minimal Wear (MW)', false, 973.47, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (38, 'Isaac, UMP-45', 'Factory New (FN)', false, 92.25, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (54, 'Hydra, M4A1-S', 'Battle-Scarred (BS)', false, 821.99, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (80, 'Primal Saber, Five-SeveN', 'Minimal Wear (MW)', false, 664.9, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (70, 'Asiimov, FAMAS', 'Well-Worn (WW)', true, 264.11, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (50, 'Dragon Lore, USP-S', 'Field-Tested (FT)', false, 321.91, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (69, 'Mecha Industries, Tec-9', 'Well-Worn (WW)', true, 349.86, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (4, 'Monkey Business, SG 553', 'Factory New (FN)', false, 470.53, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (50, 'Neon Rider', 'Field-Tested (FT)', false, 835.96, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (37, 'Monkey Business, SG 553', 'Factory New (FN)', false, 141.1, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (24, 'Fade, Desert Eagle', 'Factory New (FN)', false, 301.03, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (9, 'Rocket Pop, MP9', 'Field-Tested (FT)', false, 643.42, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (56, 'Hyper Beast, XM1014', 'Minimal Wear (MW)', true, 894.96, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (100, 'Primal Saber, Five-SeveN', 'Factory New (FN)', false, 511.48, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (25, 'Asiimov, FAMAS', 'Well-Worn (WW)', false, 996.41, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (52, 'Roll Cage, Galil AR', 'Field-Tested (FT)', true, 36.52, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (81, 'Rocket Pop, MP9', 'Field-Tested (FT)', false, 456.86, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (1, 'Vulcan, M4A4', 'Battle-Scarred (BS)', true, 891.33, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (20, 'Hyper Beast, XM1014', 'Minimal Wear (MW)', false, 597.16, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (46, 'Vulcan, M4A4', 'Field-Tested (FT)', true, 241.86, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (98, 'AK-47', 'Well-Worn (WW)', false, 262.02, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (33, 'Primal Saber, Five-SeveN', 'Minimal Wear (MW)', true, 285.6, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (38, 'Monkey Business, SG 553', 'Field-Tested (FT)', false, 754.94, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (7, 'Hydra, M4A1-S', 'Minimal Wear (MW)', false, 362.49, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (52, 'Hyper Beast, XM1014', 'Battle-Scarred (BS)', false, 422.73, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (73, 'Vulcan, M4A4', 'Field-Tested (FT)', false, 34.96, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (74, 'Hyper Beast, XM1014', 'Well-Worn (WW)', false, 249.91, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (55, 'Fade, Desert Eagle', 'Factory New (FN)', true, 256.62, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (54, 'Mecha Industries, Tec-9', 'Well-Worn (WW)', false, 689.28, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (9, 'Hydra, M4A1-S', 'Field-Tested (FT)', false, 585.03, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (3, 'Blood in the Water, P90', 'Well-Worn (WW)', true, 701.52, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (62, 'Monkey Business, SG 553', 'Well-Worn (WW)', true, 823.74, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (22, 'Blaze, P250', 'Battle-Scarred (BS)', false, 212.58, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (56, 'Monkey Business, SG 553', 'Battle-Scarred (BS)', false, 238.72, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (13, 'Roll Cage, Galil AR', 'Well-Worn (WW)', true, 805.66, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (36, 'Hyper Beast, XM1014', 'Minimal Wear (MW)', true, 506.82, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (84, 'AK-47', 'Field-Tested (FT)', true, 172.74, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (25, 'Roll Cage, Galil AR', 'Factory New (FN)', true, 558.91, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (70, 'Asiimov, Nova', 'Battle-Scarred (BS)', false, 173.72, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (57, 'Isaac, UMP-45', 'Battle-Scarred (BS)', true, 421.27, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (45, 'Asiimov, Nova', 'Battle-Scarred (BS)', false, 70.6, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (18, 'Roll Cage, Galil AR', 'Minimal Wear (MW)', false, 939.23, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (56, 'Vulcan, M4A4', 'Minimal Wear (MW)', true, 772.92, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (93, 'Vulcan, M4A4', 'Battle-Scarred (BS)', true, 852.89, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (18, 'Hydra, M4A1-S', 'Battle-Scarred (BS)', true, 484.37, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (82, 'Rocket Pop, MP9', 'Minimal Wear (MW)', false, 25.67, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (18, 'Asiimov, Nova', 'Field-Tested (FT)', false, 56.71, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (44, 'Asiimov, FAMAS', 'Well-Worn (WW)', true, 429.87, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (25, 'Hydra, M4A1-S', 'Field-Tested (FT)', true, 104.34, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (36, 'Asiimov, Nova', 'Well-Worn (WW)', false, 716.22, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (22, 'Black Tie, MAC-10', 'Well-Worn (WW)', false, 224.11, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (65, 'Blood in the Water, P90', 'Well-Worn (WW)', false, 141.99, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (73, 'Pulse, SSG 08', 'Battle-Scarred (BS)', false, 85.63, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (50, 'AK-47', 'Factory New (FN)', true, 347.43, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (56, 'Asiimov, Nova', 'Field-Tested (FT)', false, 559.51, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (95, 'Roll Cage, Galil AR', 'Factory New (FN)', true, 930.92, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (90, 'Blood in the Water, P90', 'Minimal Wear (MW)', false, 656.14, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (29, 'Mecha Industries, Tec-9', 'Minimal Wear (MW)', true, 923.88, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (79, 'Neon Rider', 'Minimal Wear (MW)', false, 712.78, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (41, 'Mecha Industries, Tec-9', 'Well-Worn (WW)', false, 985.73, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (88, 'Black Tie, MAC-10', 'Factory New (FN)', false, 400.93, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (20, 'Black Tie, MAC-10', 'Well-Worn (WW)', false, 832.2, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (43, 'Monkey Business, SG 553', 'Factory New (FN)', true, 271.7, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (98, 'Neon Rider', 'Factory New (FN)', false, 258.49, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (9, 'Vulcan, M4A4', 'Factory New (FN)', false, 570.8, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (100, 'Mecha Industries, Tec-9', 'Field-Tested (FT)', false, 702.12, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (46, 'Roll Cage, Galil AR', 'Well-Worn (WW)', false, 960.68, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (35, 'Dragon Lore, USP-S', 'Battle-Scarred (BS)', true, 273.51, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (44, 'Blaze, P250', 'Field-Tested (FT)', true, 747.22, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (9, 'Primal Saber, Five-SeveN', 'Field-Tested (FT)', true, 421.1, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (100, 'Roll Cage, Galil AR', 'Factory New (FN)', false, 108.95, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (88, 'Kill Confirmed, Glock-18', 'Factory New (FN)', false, 195.92, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (53, 'Blaze, P250', 'Minimal Wear (MW)', false, 834.57, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (26, 'Pulse, SSG 08', 'Battle-Scarred (BS)', false, 997.62, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (12, 'Hyper Beast, XM1014', 'Factory New (FN)', true, 872.05, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (66, 'Kill Confirmed, Glock-18', 'Battle-Scarred (BS)', true, 106.98, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (80, 'Black Tie, MAC-10', 'Minimal Wear (MW)', false, 21.06, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (76, 'AK-47', 'Battle-Scarred (BS)', false, 304.48, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (92, 'Black Tie, MAC-10', 'Field-Tested (FT)', true, 141.08, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (43, 'Dragon Lore, USP-S', 'Battle-Scarred (BS)', false, 20.54, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (71, 'Vulcan, M4A4', 'Minimal Wear (MW)', false, 521.91, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (16, 'Neon Rider', 'Minimal Wear (MW)', true, 135.93, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (96, 'Asiimov, FAMAS', 'Factory New (FN)', true, 694.32, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (9, 'Howl, AWP', 'Field-Tested (FT)', false, 486.7, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (65, 'Roll Cage, Galil AR', 'Minimal Wear (MW)', true, 581.52, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (13, 'Kill Confirmed, Glock-18', 'Well-Worn (WW)', true, 537.66, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (35, 'Hydra, M4A1-S', 'Field-Tested (FT)', false, 937.75, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (80, 'Hydra, M4A1-S', 'Factory New (FN)', true, 408.55, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (51, 'Neon Rider', 'Factory New (FN)', true, 480.31, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (77, 'Vulcan, M4A4', 'Well-Worn (WW)', true, 884.68, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (22, 'Hyper Beast, XM1014', 'Battle-Scarred (BS)', false, 243.61, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (93, 'Hydra, M4A1-S', 'Field-Tested (FT)', false, 456.42, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (55, 'Kill Confirmed, Glock-18', 'Well-Worn (WW)', false, 491.88, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (10, 'Pulse, SSG 08', 'Battle-Scarred (BS)', true, 831.24, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (54, 'Monkey Business, SG 553', 'Battle-Scarred (BS)', true, 537.66, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (35, 'Pulse, SSG 08', 'Field-Tested (FT)', true, 541.7, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (33, 'Monkey Business, SG 553', 'Field-Tested (FT)', false, 120.66, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (98, 'Vulcan, M4A4', 'Field-Tested (FT)', true, 371.01, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (33, 'Kill Confirmed, Glock-18', 'Factory New (FN)', true, 542.73, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (71, 'Rocket Pop, MP9', 'Minimal Wear (MW)', false, 84.97, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (71, 'Black Tie, MAC-10', 'Factory New (FN)', false, 734.63, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (92, 'Fade, Desert Eagle', 'Well-Worn (WW)', false, 187.41, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (36, 'Asiimov, Nova', 'Battle-Scarred (BS)', false, 641.45, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (8, 'Howl, AWP', 'Factory New (FN)', true, 219.6, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (29, 'Dragon Lore, USP-S', 'Minimal Wear (MW)', false, 308.54, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (12, 'Fade, Desert Eagle', 'Field-Tested (FT)', true, 795.65, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (37, 'Primal Saber, Five-SeveN', 'Field-Tested (FT)', false, 715.89, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (55, 'Monkey Business, SG 553', 'Minimal Wear (MW)', true, 435.58, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (49, 'Black Tie, MAC-10', 'Field-Tested (FT)', true, 270.17, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (19, 'Neon Rider', 'Well-Worn (WW)', true, 447.95, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (100, 'Primal Saber, Five-SeveN', 'Factory New (FN)', true, 665.19, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (3, 'Neon Rider', 'Field-Tested (FT)', true, 982.5, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (69, 'Blaze, P250', 'Factory New (FN)', false, 426.43, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (30, 'Roll Cage, Galil AR', 'Minimal Wear (MW)', false, 611.71, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (33, 'Asiimov, FAMAS', 'Factory New (FN)', false, 548.56, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (58, 'Roll Cage, Galil AR', 'Battle-Scarred (BS)', true, 618.29, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (86, 'Asiimov, Nova', 'Well-Worn (WW)', false, 183.03, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (54, 'Pulse, SSG 08', 'Factory New (FN)', false, 363.38, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (9, 'Roll Cage, Galil AR', 'Factory New (FN)', false, 947.84, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (22, 'Asiimov, FAMAS', 'Battle-Scarred (BS)', true, 144.19, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (10, 'Asiimov, FAMAS', 'Well-Worn (WW)', false, 765.75, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (71, 'Primal Saber, Five-SeveN', 'Well-Worn (WW)', true, 652.98, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (83, 'Blaze, P250', 'Factory New (FN)', false, 83.26, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (23, 'Isaac, UMP-45', 'Battle-Scarred (BS)', true, 936.07, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (2, 'Hyper Beast, XM1014', 'Factory New (FN)', false, 493.84, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (60, 'AK-47', 'Battle-Scarred (BS)', true, 170.89, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (75, 'Hyper Beast, XM1014', 'Battle-Scarred (BS)', false, 927.06, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (1, 'Isaac, UMP-45', 'Battle-Scarred (BS)', false, 642.87, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (3, 'Mecha Industries, Tec-9', 'Factory New (FN)', false, 495.32, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (57, 'Black Tie, MAC-10', 'Battle-Scarred (BS)', false, 182.02, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (78, 'Howl, AWP', 'Factory New (FN)', false, 862.75, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (67, 'Blood in the Water, P90', 'Minimal Wear (MW)', true, 822.72, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (94, 'Hydra, M4A1-S', 'Well-Worn (WW)', true, 429.31, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (14, 'Neon Rider', 'Battle-Scarred (BS)', false, 975.01, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (29, 'Vulcan, M4A4', 'Minimal Wear (MW)', false, 519.02, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (30, 'Neon Rider', 'Minimal Wear (MW)', true, 996.5, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (74, 'Blood in the Water, P90', 'Minimal Wear (MW)', false, 481.55, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (49, 'Pulse, SSG 08', 'Well-Worn (WW)', true, 979.85, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (44, 'Blaze, P250', 'Well-Worn (WW)', true, 111.29, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (18, 'Monkey Business, SG 553', 'Field-Tested (FT)', true, 677.44, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (23, 'Black Tie, MAC-10', 'Factory New (FN)', false, 353.73, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (76, 'Dragon Lore, USP-S', 'Factory New (FN)', false, 645.57, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (78, 'Rocket Pop, MP9', 'Battle-Scarred (BS)', false, 193.18, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (2, 'Neon Rider', 'Field-Tested (FT)', false, 612.18, false);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (57, 'Neon Rider', 'Minimal Wear (MW)', true, 236.88, true);
insert into inventory (player_id, gun_name, gun_status, gun_ST, gun_price, on_sale) values (14, 'Hydra, M4A1-S', 'Minimal Wear (MW)', true, 848.79, false);